% -------------------------------------------------------------------
%  Generated by MATLAB on 17-Sep-2026 17:19:33
%  MATLAB version: 26.1.0.3346908 (R2026a) Update 5
% -------------------------------------------------------------------
saveVarsMat = load('Lecture01_signal_visualization.mat');

amplitude = 1;

amps = [0.5 1 2];

cleanSignal = saveVarsMat.cleanSignal; % <1x1001 double> 元素太多

duration = 1;

fig1 = saveVarsMat.fig1; % <1x1 matlab.ui.Figure> 不支持的类

fig2 = saveVarsMat.fig2; % <1x1 matlab.ui.Figure> 不支持的类

fig3 = saveVarsMat.fig3; % <1x1 matlab.ui.Figure> 不支持的类

fig4 = saveVarsMat.fig4; % <1x1 matlab.ui.Figure> 不支持的类

freqs = [2 5 10];

frequency = 5;

fs = 1000;

k = 3;

noise = saveVarsMat.noise; % <1x1001 double> 元素太多

noisySignal = saveVarsMat.noisySignal; % <1x1001 double> 元素太多

sineWave = saveVarsMat.sineWave; % <1x1001 double> 元素太多

t = saveVarsMat.t; % <1x1001 double> 元素太多

y = saveVarsMat.y; % <1x1001 double> 元素太多

clear saveVarsMat;
